# https://taskfile.dev

version: "3"

vars:
  VERSION: 0.1.0

tasks:
  bump:
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push --tags
      - GOPROXY=proxy.golang.org go list -m github.com/delaneyj/toolbelt@v{{.VERSION}}
  # default:
  # silent: true
