# https://taskfile.dev

version: "3"

vars:
  VERSION: 0.3.3

interval: 200ms

tasks:
  tools:
    cmds:
      - go get -u github.com/valyala/quicktemplate/qtc
      - go install github.com/valyala/quicktemplate/qtc@latest
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

  libpub:
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push --tags
      - GOPROXY=proxy.golang.org go list -m github.com/delaneyj/toolbelt@v{{.VERSION}}

  qtc:
    sources:
      - "**/*.qtpl"
    generates:
      - "**/*.qtpl.go"
    cmds:
      - qtc

  sqlc-examples:
    dir: sqlc-gen-zombiezen/zombiezen/examples
    cmds:
      - sqlc generate
      - goimports -w .

  sqlc:
    dir: sqlc-gen-zombiezen
    deps:
      - qtc
    sources:
      - "**/*.go"
      - exclude: "**.qtpl.go"
    cmds:
      - go install
      - task sqlc-examples
